//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.2-b01-fcs
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2010.06.15 at 09:44:57 AM EDT
//

package edu.harvard.i2b2.crc.datavo.setfinder.query;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for query_result_typeType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="query_result_typeType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="result_type_id" type="{http://www.i2b2.org/xsd/cell/crc/psm/1.1/}result_type_idType"/>
 *         &lt;element name="name" type="{http://www.i2b2.org/xsd/cell/crc/psm/1.1/}nameType" minOccurs="0"/>
 *         &lt;element name="display_type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="visual_attribute_type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="description" type="{http://www.i2b2.org/xsd/cell/crc/psm/1.1/}descriptionType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "query_result_typeType", propOrder = { "resultTypeId", "name", "displayType", "visualAttributeType", "description" })
public class QueryResultTypeType
{

    @XmlElement(name = "result_type_id", required = true)
    protected String resultTypeId;
    protected String name;
    @XmlElement(name = "display_type")
    protected String displayType;
    @XmlElement(name = "visual_attribute_type")
    protected String visualAttributeType;
    protected String description;

    /**
     * Gets the value of the resultTypeId property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getResultTypeId()
    {
        return resultTypeId;
    }

    /**
     * Sets the value of the resultTypeId property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setResultTypeId(final String value)
    {
        resultTypeId = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getName()
    {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setName(final String value)
    {
        name = value;
    }

    /**
     * Gets the value of the displayType property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getDisplayType()
    {
        return displayType;
    }

    /**
     * Sets the value of the displayType property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setDisplayType(final String value)
    {
        displayType = value;
    }

    /**
     * Gets the value of the visualAttributeType property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getVisualAttributeType()
    {
        return visualAttributeType;
    }

    /**
     * Sets the value of the visualAttributeType property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setVisualAttributeType(final String value)
    {
        visualAttributeType = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getDescription()
    {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setDescription(final String value)
    {
        description = value;
    }

    @Override
    public int hashCode()
    {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((description == null) ? 0 : description.hashCode());
        result = prime * result + ((displayType == null) ? 0 : displayType.hashCode());
        result = prime * result + ((name == null) ? 0 : name.hashCode());
        result = prime * result + ((resultTypeId == null) ? 0 : resultTypeId.hashCode());
        result = prime * result + ((visualAttributeType == null) ? 0 : visualAttributeType.hashCode());
        return result;
    }

    @Override
    public boolean equals(final Object obj)
    {
        if(this == obj)
        {
            return true;
        }
        if(obj == null)
        {
            return false;
        }
        if(getClass() != obj.getClass())
        {
            return false;
        }
        final QueryResultTypeType other = (QueryResultTypeType) obj;
        if(description == null)
        {
            if(other.description != null)
            {
                return false;
            }
        }
        else if(!description.equals(other.description))
        {
            return false;
        }
        if(displayType == null)
        {
            if(other.displayType != null)
            {
                return false;
            }
        }
        else if(!displayType.equals(other.displayType))
        {
            return false;
        }
        if(name == null)
        {
            if(other.name != null)
            {
                return false;
            }
        }
        else if(!name.equals(other.name))
        {
            return false;
        }
        if(resultTypeId == null)
        {
            if(other.resultTypeId != null)
            {
                return false;
            }
        }
        else if(!resultTypeId.equals(other.resultTypeId))
        {
            return false;
        }
        if(visualAttributeType == null)
        {
            if(other.visualAttributeType != null)
            {
                return false;
            }
        }
        else if(!visualAttributeType.equals(other.visualAttributeType))
        {
            return false;
        }
        return true;
    }

    @Override
    public String toString()
    {
        return "QueryResultTypeType [resultTypeId=" + resultTypeId + ", name=" + name + ", displayType=" + displayType + ", visualAttributeType=" + visualAttributeType + ", description=" + description + "]";
    }
}
