//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.2-b01-fcs
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2010.06.15 at 09:44:57 AM EDT
//

package edu.harvard.i2b2.crc.datavo.setfinder.query;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * <p>
 * Java class for query_result_instanceType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="query_result_instanceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="result_instance_id" type="{http://www.i2b2.org/xsd/cell/crc/psm/1.1/}result_instance_idType"/>
 *         &lt;element name="query_instance_id" type="{http://www.i2b2.org/xsd/cell/crc/psm/1.1/}query_instance_idType"/>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="query_result_type" type="{http://www.i2b2.org/xsd/cell/crc/psm/1.1/}query_result_typeType"/>
 *         &lt;element name="set_size" type="{http://www.i2b2.org/xsd/cell/crc/psm/1.1/}set_sizeType"/>
 *         &lt;element name="obfuscate_method" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="start_date" type="{http://www.i2b2.org/xsd/cell/crc/psm/1.1/}start_dateType"/>
 *         &lt;element name="end_date" type="{http://www.i2b2.org/xsd/cell/crc/psm/1.1/}end_dateType"/>
 *         &lt;element name="message" type="{http://www.i2b2.org/xsd/cell/crc/psm/1.1/}xml_valueType"/>
 *         &lt;element name="query_status_type" type="{http://www.i2b2.org/xsd/cell/crc/psm/1.1/}query_status_typeType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlRootElement(name = "query_result_instance")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "query_result_instanceType", propOrder = { "resultInstanceId", "queryInstanceId", "description", "queryResultType", "setSize", "obfuscateMethod", "startDate", "endDate", "message", "queryStatusType" })
public class QueryResultInstanceType
{

    @XmlElement(name = "result_instance_id", required = true)
    protected String resultInstanceId;
    @XmlElement(name = "query_instance_id", required = true)
    protected String queryInstanceId;
    protected String description;
    @XmlElement(name = "query_result_type", required = true)
    protected QueryResultTypeType queryResultType;
    @XmlElement(name = "set_size")
    protected int setSize;
    @XmlElement(name = "obfuscate_method", required = true)
    protected String obfuscateMethod;
    @XmlElement(name = "start_date", required = true)
    protected XMLGregorianCalendar startDate;
    @XmlElement(name = "end_date", required = true)
    protected XMLGregorianCalendar endDate;
    @XmlElement(required = true)
    protected XmlValueType message;
    @XmlElement(name = "query_status_type", required = true)
    protected QueryStatusTypeType queryStatusType;

    /**
     * Gets the value of the resultInstanceId property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getResultInstanceId()
    {
        return resultInstanceId;
    }

    /**
     * Sets the value of the resultInstanceId property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setResultInstanceId(final String value)
    {
        resultInstanceId = value;
    }

    /**
     * Gets the value of the queryInstanceId property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getQueryInstanceId()
    {
        return queryInstanceId;
    }

    /**
     * Sets the value of the queryInstanceId property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setQueryInstanceId(final String value)
    {
        queryInstanceId = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getDescription()
    {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setDescription(final String value)
    {
        description = value;
    }

    /**
     * Gets the value of the queryResultType property.
     * 
     * @return possible object is {@link QueryResultTypeType }
     * 
     */
    public QueryResultTypeType getQueryResultType()
    {
        return queryResultType;
    }

    /**
     * Sets the value of the queryResultType property.
     * 
     * @param value
     *            allowed object is {@link QueryResultTypeType }
     * 
     */
    public void setQueryResultType(final QueryResultTypeType value)
    {
        queryResultType = value;
    }

    /**
     * Gets the value of the setSize property.
     * 
     */
    public int getSetSize()
    {
        return setSize;
    }

    /**
     * Sets the value of the setSize property.
     * 
     */
    public void setSetSize(final int value)
    {
        setSize = value;
    }

    /**
     * Gets the value of the obfuscateMethod property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getObfuscateMethod()
    {
        return obfuscateMethod;
    }

    /**
     * Sets the value of the obfuscateMethod property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setObfuscateMethod(final String value)
    {
        obfuscateMethod = value;
    }

    /**
     * Gets the value of the startDate property.
     * 
     * @return possible object is
     *         {@link javax.xml.datatype.XMLGregorianCalendar }
     * 
     */
    public XMLGregorianCalendar getStartDate()
    {
        return startDate;
    }

    /**
     * Sets the value of the startDate property.
     * 
     * @param value
     *            allowed object is
     *            {@link javax.xml.datatype.XMLGregorianCalendar }
     * 
     */
    public void setStartDate(final XMLGregorianCalendar value)
    {
        startDate = value;
    }

    /**
     * Gets the value of the endDate property.
     * 
     * @return possible object is
     *         {@link javax.xml.datatype.XMLGregorianCalendar }
     * 
     */
    public XMLGregorianCalendar getEndDate()
    {
        return endDate;
    }

    /**
     * Sets the value of the endDate property.
     * 
     * @param value
     *            allowed object is
     *            {@link javax.xml.datatype.XMLGregorianCalendar }
     * 
     */
    public void setEndDate(final XMLGregorianCalendar value)
    {
        endDate = value;
    }

    /**
     * Gets the value of the message property.
     * 
     * @return possible object is {@link XmlValueType }
     * 
     */
    public XmlValueType getMessage()
    {
        return message;
    }

    /**
     * Sets the value of the message property.
     * 
     * @param value
     *            allowed object is {@link XmlValueType }
     * 
     */
    public void setMessage(final XmlValueType value)
    {
        message = value;
    }

    /**
     * Gets the value of the queryStatusType property.
     * 
     * @return possible object is {@link QueryStatusTypeType }
     * 
     */
    public QueryStatusTypeType getQueryStatusType()
    {
        return queryStatusType;
    }

    /**
     * Sets the value of the queryStatusType property.
     * 
     * @param value
     *            allowed object is {@link QueryStatusTypeType }
     * 
     */
    public void setQueryStatusType(final QueryStatusTypeType value)
    {
        queryStatusType = value;
    }

    //NB: Only compare using IDs
    @Override
    public int hashCode()
    {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((queryInstanceId == null) ? 0 : queryInstanceId.hashCode());
        result = prime * result + ((resultInstanceId == null) ? 0 : resultInstanceId.hashCode());
        return result;
    }

    //NB: Only compare using IDs
    @Override
    public boolean equals(Object obj)
    {
        if(this == obj)
        {
            return true;
        }
        if(obj == null)
        {
            return false;
        }
        if(getClass() != obj.getClass())
        {
            return false;
        }
        QueryResultInstanceType other = (QueryResultInstanceType) obj;
        if(queryInstanceId == null)
        {
            if(other.queryInstanceId != null)
            {
                return false;
            }
        }
        else if(!queryInstanceId.equals(other.queryInstanceId))
        {
            return false;
        }
        if(resultInstanceId == null)
        {
            if(other.resultInstanceId != null)
            {
                return false;
            }
        }
        else if(!resultInstanceId.equals(other.resultInstanceId))
        {
            return false;
        }
        return true;
    }

    @Override
    public String toString()
    {
        return "QueryResultInstanceType [resultInstanceId=" + resultInstanceId + ", queryInstanceId=" + queryInstanceId + ", description=" + description + ", queryResultType=" + queryResultType + ", setSize=" + setSize + ", obfuscateMethod=" + obfuscateMethod + ", startDate=" + startDate + ", endDate=" + endDate + ", message=" + message + ", queryStatusType=" + queryStatusType + "]";
    }
}
