//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.2-b01-fcs
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2010.06.15 at 09:44:57 AM EDT
//

package edu.harvard.i2b2.crc.datavo.setfinder.query;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for query_status_typeType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="query_status_typeType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="status_type_id" type="{http://www.i2b2.org/xsd/cell/crc/psm/1.1/}status_type_idType"/>
 *         &lt;element name="name" type="{http://www.i2b2.org/xsd/cell/crc/psm/1.1/}nameType" minOccurs="0"/>
 *         &lt;element name="description" type="{http://www.i2b2.org/xsd/cell/crc/psm/1.1/}descriptionType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "query_status_typeType", propOrder = { "statusTypeId", "name", "description" })
public class QueryStatusTypeType
{

    @XmlElement(name = "status_type_id", required = true)
    protected String statusTypeId;
    protected String name;
    protected String description;

    /**
     * Gets the value of the statusTypeId property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getStatusTypeId()
    {
        return statusTypeId;
    }

    /**
     * Sets the value of the statusTypeId property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setStatusTypeId(final String value)
    {
        statusTypeId = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getName()
    {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setName(final String value)
    {
        name = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getDescription()
    {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setDescription(final String value)
    {
        description = value;
    }

    @Override
    public int hashCode()
    {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((description == null) ? 0 : description.hashCode());
        result = prime * result + ((name == null) ? 0 : name.hashCode());
        result = prime * result + ((statusTypeId == null) ? 0 : statusTypeId.hashCode());
        return result;
    }

    @Override
    public boolean equals(final Object obj)
    {
        if(this == obj)
        {
            return true;
        }
        if(obj == null)
        {
            return false;
        }
        if(getClass() != obj.getClass())
        {
            return false;
        }
        final QueryStatusTypeType other = (QueryStatusTypeType) obj;
        if(description == null)
        {
            if(other.description != null)
            {
                return false;
            }
        }
        else if(!description.equals(other.description))
        {
            return false;
        }
        if(name == null)
        {
            if(other.name != null)
            {
                return false;
            }
        }
        else if(!name.equals(other.name))
        {
            return false;
        }
        if(statusTypeId == null)
        {
            if(other.statusTypeId != null)
            {
                return false;
            }
        }
        else if(!statusTypeId.equals(other.statusTypeId))
        {
            return false;
        }
        return true;
    }

    @Override
    public String toString()
    {
        return "QueryStatusTypeType [statusTypeId=" + statusTypeId + ", name=" + name + ", description=" + description + "]";
    }
}
