//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.2-b01-fcs
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2010.06.15 at 09:44:57 AM EDT
//

package edu.harvard.i2b2.crc.datavo.setfinder.query;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * <p>
 * Java class for query_masterType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="query_masterType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="query_master_id" type="{http://www.i2b2.org/xsd/cell/crc/psm/1.1/}query_master_idType"/>
 *         &lt;element name="name" type="{http://www.i2b2.org/xsd/cell/crc/psm/1.1/}nameType"/>
 *         &lt;element name="user_id" type="{http://www.i2b2.org/xsd/cell/crc/psm/1.1/}user_idType"/>
 *         &lt;element name="group_id" type="{http://www.i2b2.org/xsd/cell/crc/psm/1.1/}group_idType"/>
 *         &lt;element name="create_date" type="{http://www.i2b2.org/xsd/cell/crc/psm/1.1/}create_dateType"/>
 *         &lt;element name="delete_date" type="{http://www.i2b2.org/xsd/cell/crc/psm/1.1/}delete_dateType"/>
 *         &lt;element name="request_xml" type="{http://www.i2b2.org/xsd/cell/crc/psm/1.1/}request_xmlType"/>
 *         &lt;element name="generated_sql" type="{http://www.i2b2.org/xsd/cell/crc/psm/1.1/}generated_sqlType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "query_masterType", propOrder = { "queryMasterId", "name", "userId", "groupId", "createDate", "deleteDate", "requestXml", "generatedSql" })
public class QueryMasterType
{

    @XmlElement(name = "query_master_id", required = true)
    protected String queryMasterId;
    @XmlElement(required = true)
    protected String name;
    @XmlElement(name = "user_id", required = true)
    protected String userId;
    @XmlElement(name = "group_id", required = true)
    protected String groupId;
    @XmlElement(name = "create_date", required = true)
    protected XMLGregorianCalendar createDate;
    @XmlElement(name = "delete_date", required = true)
    protected XMLGregorianCalendar deleteDate;
    @XmlElement(name = "request_xml", required = true)
    protected RequestXmlType requestXml;
    @XmlElement(name = "generated_sql", required = true)
    protected String generatedSql;

    /**
     * Gets the value of the queryMasterId property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getQueryMasterId()
    {
        return queryMasterId;
    }

    /**
     * Sets the value of the queryMasterId property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setQueryMasterId(final String value)
    {
        queryMasterId = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getName()
    {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setName(final String value)
    {
        name = value;
    }

    /**
     * Gets the value of the userId property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getUserId()
    {
        return userId;
    }

    /**
     * Sets the value of the userId property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setUserId(final String value)
    {
        userId = value;
    }

    /**
     * Gets the value of the groupId property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getGroupId()
    {
        return groupId;
    }

    /**
     * Sets the value of the groupId property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setGroupId(final String value)
    {
        groupId = value;
    }

    /**
     * Gets the value of the createDate property.
     * 
     * @return possible object is
     *         {@link javax.xml.datatype.XMLGregorianCalendar }
     * 
     */
    public XMLGregorianCalendar getCreateDate()
    {
        return createDate;
    }

    /**
     * Sets the value of the createDate property.
     * 
     * @param value
     *            allowed object is
     *            {@link javax.xml.datatype.XMLGregorianCalendar }
     * 
     */
    public void setCreateDate(final XMLGregorianCalendar value)
    {
        createDate = value;
    }

    /**
     * Gets the value of the deleteDate property.
     * 
     * @return possible object is
     *         {@link javax.xml.datatype.XMLGregorianCalendar }
     * 
     */
    public XMLGregorianCalendar getDeleteDate()
    {
        return deleteDate;
    }

    /**
     * Sets the value of the deleteDate property.
     * 
     * @param value
     *            allowed object is
     *            {@link javax.xml.datatype.XMLGregorianCalendar }
     * 
     */
    public void setDeleteDate(final XMLGregorianCalendar value)
    {
        deleteDate = value;
    }

    /**
     * Gets the value of the requestXml property.
     * 
     * @return possible object is {@link RequestXmlType }
     * 
     */
    public RequestXmlType getRequestXml()
    {
        return requestXml;
    }

    /**
     * Sets the value of the requestXml property.
     * 
     * @param value
     *            allowed object is {@link RequestXmlType }
     * 
     */
    public void setRequestXml(final RequestXmlType value)
    {
        requestXml = value;
    }

    /**
     * Gets the value of the generatedSql property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getGeneratedSql()
    {
        return generatedSql;
    }

    /**
     * Sets the value of the generatedSql property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setGeneratedSql(final String value)
    {
        generatedSql = value;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        QueryMasterType that = (QueryMasterType) o;

        if (generatedSql != null ? !generatedSql.equals(that.generatedSql) : that.generatedSql != null) return false;
        if (groupId != null ? !groupId.equals(that.groupId) : that.groupId != null) return false;
        if (name != null ? !name.equals(that.name) : that.name != null) return false;
        if (queryMasterId != null ? !queryMasterId.equals(that.queryMasterId) : that.queryMasterId != null)
            return false;
        if (requestXml != null ? !requestXml.equals(that.requestXml) : that.requestXml != null) return false;
        if (userId != null ? !userId.equals(that.userId) : that.userId != null) return false;

        return true;
    }

    @Override
    public int hashCode() {
        int result = queryMasterId != null ? queryMasterId.hashCode() : 0;
        result = 31 * result + (name != null ? name.hashCode() : 0);
        result = 31 * result + (userId != null ? userId.hashCode() : 0);
        result = 31 * result + (groupId != null ? groupId.hashCode() : 0);
        result = 31 * result + (requestXml != null ? requestXml.hashCode() : 0);
        result = 31 * result + (generatedSql != null ? generatedSql.hashCode() : 0);
        return result;
    }

    @Override
    public String toString()
    {
        return "QueryMasterType [queryMasterId=" + queryMasterId + ", name=" + name + ", userId=" + userId + ", groupId=" + groupId + ", createDate=" + createDate + ", deleteDate=" + deleteDate + ", requestXml=" + requestXml + ", generatedSql=" + generatedSql + "]";
    }
}
