//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.2-b01-fcs
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2010.06.15 at 09:44:57 AM EDT
//

package edu.harvard.i2b2.crc.datavo.setfinder.query;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;

/**
 * responseType is abstract so a concrete type must be declared in the instance
 * document using the xsi:type attribute.
 * 
 * <p>
 * Java class for responseType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="responseType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="status" type="{http://www.i2b2.org/xsd/cell/crc/psm/1.1/}statusType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "responseType", propOrder = { "status" })
@XmlSeeAlso({ RequestXmlResponseType.class, InstanceResultResponseType.class, CrcXmlResultResponseType.class, MasterInstanceResultResponseType.class, MasterResponseType.class, ResultResponseType.class, PatientSetResponseType.class, ResultTypeResponseType.class, InstanceResponseType.class })
public abstract class ResponseType
{

    @XmlElement(required = true)
    protected StatusType status;

    /**
     * Gets the value of the status property.
     * 
     * @return possible object is {@link StatusType }
     * 
     */
    public StatusType getStatus()
    {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *            allowed object is {@link StatusType }
     * 
     */
    public void setStatus(final StatusType value)
    {
        status = value;
    }

    @Override
    public int hashCode()
    {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((status == null) ? 0 : status.hashCode());
        return result;
    }

    @Override
    public boolean equals(final Object obj)
    {
        if(this == obj)
        {
            return true;
        }
        if(obj == null)
        {
            return false;
        }
        if(getClass() != obj.getClass())
        {
            return false;
        }
        final ResponseType other = (ResponseType) obj;
        if(status == null)
        {
            if(other.status != null)
            {
                return false;
            }
        }
        else if(!status.equals(other.status))
        {
            return false;
        }
        return true;
    }

    @Override
    public String toString()
    {
        return "ResponseType [status=" + status + "]";
    }
}
