//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.2-b01-fcs
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2010.06.15 at 09:44:57 AM EDT
//

package edu.harvard.i2b2.crc.datavo.setfinder.query;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;

/**
 * <p/>
 * Java class for result_responseType complex type.
 * <p/>
 * <p/>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * <p/>
 * <pre>
 * &lt;complexType name="result_responseType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.i2b2.org/xsd/cell/crc/psm/1.1/}responseType">
 *       &lt;sequence>
 *         &lt;element name="query_result_instance" type="{http://www.i2b2.org/xsd/cell/crc/psm/1.1/}query_result_instanceType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlRootElement(name = "response")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "result_responseType", propOrder = {"queryResultInstance"})
public class ResultResponseType extends ResponseType
{
    @XmlElement(name = "query_result_instance", required = true)
    protected List<QueryResultInstanceType> queryResultInstance;

    /**
     * Gets the value of the queryResultInstance property.
     * <p/>
     * <p/>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the queryResultInstance property.
     * <p/>
     * <p/>
     * For example, to add a new item, do as follows:
     * <p/>
     * <pre>
     * getQueryResultInstance().add(newItem);
     * </pre>
     * <p/>
     * <p/>
     * <p/>
     * Objects of the following type(s) are allowed in the list
     * {@link edu.harvard.i2b2.crc.datavo.setfinder.query.QueryResultInstanceType }
     */
    public List<QueryResultInstanceType> getQueryResultInstance()
    {
        if(queryResultInstance == null)
        {
            queryResultInstance = new ArrayList<QueryResultInstanceType>();
        }
        return queryResultInstance;
    }

    @Override
    public int hashCode()
    {
        final int prime = 31;
        int result = super.hashCode();
        result = prime * result + ((queryResultInstance == null) ? 0 : queryResultInstance.hashCode());
        return result;
    }

    @Override
    public boolean equals(final Object obj)
    {
        if(this == obj)
        {
            return true;
        }
        if(!super.equals(obj))
        {
            return false;
        }
        if(getClass() != obj.getClass())
        {
            return false;
        }
        final ResultResponseType other = (ResultResponseType) obj;
        if(queryResultInstance == null)
        {
            if(other.queryResultInstance != null)
            {
                return false;
            }
        }
        else if(!queryResultInstance.equals(other.queryResultInstance))
        {
            return false;
        }
        return true;
    }

    @Override
    public String toString()
    {
        return "ResultResponseType [queryResultInstance=" + queryResultInstance + "]";
    }
}
