#!/bin/bash

CONFIG_HOME=`dirname $0`

CONFIG_CLASSPATH=.

CONFIG_FILE_DIR=${CONFIG_HOME}/conf
LIB_DIR=${CONFIG_HOME}/lib

mkdir -p ${CONFIG_FILE_DIR}

#
#Set up our classpath with our library dependencies...
for jar in `find ${CONFIG_HOME}/lib/*.jar`;
do
    CONFIG_CLASSPATH=${jar}:${CONFIG_CLASSPATH}
done

if [ ${#JAVA_HOME} == 0 ]; then
    JAVA_HOME=/usr/local/java
fi

#JVM_ARGS="-Xmx256m"

JAVA_COMMAND="java -Dlog4j.configuration=log4j.properties -cp ${CONFIG_CLASSPATH}:${CONFIG_FILE_DIR} net.shrine.utilities.scanner.ScannerModule $@"

#echo ${JAVA_COMMAND}

${JAVA_COMMAND}

